'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var CHANGE_RANGE = exports.CHANGE_RANGE = 'CHANGE_RANGE';
var FETCH_ARTICLE_REQUEST = exports.FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';
var FETCH_ARTICLE_SUCCESS = exports.FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
var FETCH_ARTICLE_FAILURE = exports.FETCH_ARTICLE_FAILURE = 'FETCH_ARTICLE_FAILURE';